POST http://127.0.0.1:5000/perform_query
Content-Type: application/json

//{
//  "file_name": "apache_logs.txt",
//  "cmd1": "filter",
//  "value1": "1.22.35.226",
//  "cmd2": "limit",
//  "value1": "2"
//}

{
  "file_name": "apache_logs.txt",
  "cmd1": "filter",
  "value1": "1.22.35.226"
  }